### ISSUE TITLE
The setParameters method in AbstractQuery shows error on mixed type

### ISSUE THREAD

**Issue by pavlakis** [phpstan/phpstan-doctrine#105]
This is for Doctrine ORM `2.7.0`

In a Repository with the following:

```

$query = $em->createQuery('SELECT u FROM ForumUser u WHERE (u.username = :name OR u.username = :name2) AND u.id = :id');
$query->setParameters(array(
    'name' => 'Bob',
    'name2' => 'Alice',
    'id' => 321,
));
$users = $query->getResult();

```

According to the [method](https://github.com/doctrine/orm/blob/v2.7.0/lib/Doctrine/ORM/AbstractQuery.php#L343), this should be allowed:

```
* @param ArrayCollection|mixed[] $parameters
```

But instead, the following error is generated:

```
Parameter #1 $parameters of method                                       
         Doctrine\ORM\AbstractQuery::setParameters() expects                      
         Doctrine\Common\Collections\ArrayCollection&iterable, array<string,      
         string> given.  
```

**Comment by ondrejmirtes** [comment]
This is basically the same problem: https://github.com/phpstan/phpstan/issues/2494#issuecomment-539406166

`ArrayCollection|mixed[]` means `ArrayCollection of mixed`, not `ArrayCollection OR array`.

Since the `array` type is basically deprecated here, you should start using `ArrayCollection` instead.

**Comment by pavlakis** [comment]
I hadn't seen that. Thank you.
