### ISSUE TITLE
Allow EntityNotFinalRule without bleeding edge 

### ISSUE THREAD

**Issue by ruudk** [phpstan/phpstan-doctrine#170]
I want to use the EntityNotFinalRule implemented in https://github.com/phpstan/phpstan-doctrine/pull/143 but it's only available when having bleeding edge enabled.

I don't want to enable bleeding edge on my project just yet. Would it be possible to toggle this based on a parameter instead? If possible, I will create the PR.

**Comment by ondrejmirtes** [comment]
Hi, what you don't like about the rest of the bleedingEdge behaviour? Its point is to gather early feedback because all of it will be enabled in the next major version (1.0) of PHPStan.

Anyway, you can just copy the definition of the rule in your phpstan.neon which will enable it on your project, like this:

```neon
	-
		class: PHPStan\Rules\Doctrine\ORM\EntityNotFinalRule
		tags:
			- phpstan
```

**Comment by ruudk** [comment]
Thanks! It works.

I will enable BleedingEdge soon! :)
