### ISSUE TITLE
Property Entity::$id is never read, only written

### ISSUE THREAD

**Issue by simPod** [phpstan/phpstan-doctrine#177]
In phpstan bleeding edge rules this kind of error popped up on me.

Property Entity::$id is never read, only written.

```php
/** @ORM\Entity */
class Entity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid")
     */
    private UuidInterface $id;

    private function __construct(UuidInterface $id)
    {
        $this->id = $id;
    }
}
```

However, having write-only properties is IMO valid for Doctrine ORM entities. This extension should disable reporting of those errors for any class with ORM annotations `@Entity` for `@Colum` and `@XToY` (`@ManyToOne`) annotated properties.

**Comment by ondrejmirtes** [comment]
Hi, this already works, see this article: https://phpstan.org/blog/detecting-unused-private-properties-methods-constants#what-if-my-code-is-%E2%80%9Cspecial%E2%80%9D%3F

But you need to configure objectManagerLoader so that the extension can see the entity metadata: https://github.com/phpstan/phpstan-doctrine#configuration

**Comment by simPod** [comment]
Neat!
