### ISSUE TITLE
EntityManager::getRepository should return the correct EntityRepository class

### ISSUE THREAD

**Issue by teohhanhui** [phpstan/phpstan-doctrine#2]
```php
$em = $this->managerRegistry->getManager();

$travelDestinationRepository = $em->getRepository(TravelDestination::class);

$childDestinationIdsQueryBuilder = $travelDestinationRepository->getChildrenQueryBuilder($parentDestinationIds);
```

>  ------ ------------------------------------------------------------------------- 
>  Line   src/AppBundle/ApiPlatform/Doctrine/Orm/Filter/EventLocationFilter.php    
> ------ ------------------------------------------------------------------------- 
>  99     Call to an undefined method                                              
>         Doctrine\Common\Persistence\ObjectRepository::getChildrenQueryBuilder()  
>         .                                                                        
> ------ -------------------------------------------------------------------------

**Comment by Alsciende** [comment]
That would be really great!

**Comment by ondrejmirtes** [comment]
Some discussion about this is in #8.

**Comment by ondrejmirtes** [comment]
Copying my comment from the PR discussion:

Besides the point #1 from my [comment here](https://github.com/phpstan/phpstan-doctrine/pull/8#issuecomment-331131696), if you're in need of this extension, you shouldn't call `$em->getRepository()`, but inject the specific EntityRepository (or a child class) in your class directly via dependency injection, as @Ocramius said.

BTW: I'm not a fan of extending EntityRepository at all. It encourages huge god objects with many methods because of 1:1 mapping between repositories and entities. I like much more specific repositories for specific use-cases of an entity. For example one repository for getting translations, another repository for tree manipulation etc.

So I reserve my right to be opinionated and close this PR.
