### ISSUE TITLE
Database can contain string but property expects non-empty-string

### ISSUE THREAD

**Issue by DanielBadura** [phpstan/phpstan-doctrine#204]
Hello here :wave:

I just updated phpstan (0.12.91 => 0.12.94) and getting now an error which i think is here better filed.

```
Cart::$currencyCode type mapping mismatch: database can contain string but property expects non-empty-string.
```
```
    /**
     * @psalm-immutable
     *
     * @psalm-var non-empty-string
     *
     * @ORM\Column(type="string")
     */
    private string $currencyCode;
```

My question would be, how to fix the problem. I mean technically it's true, if someone edits the database i could get here an empty string. But somehow i fail to see how to fix the problem with doctrine since i dont know how i should configure the column type 🤔. Is there an option to prevent empty strings?

**Comment by AlexandruGG** [comment]
hey, I think the issue is that you have the `@psalm-var non-empty-string` annotation on your property, which is a mismatch with the doctrine type "string".

If you wanted to have a valid `non-empty-string` type you would need:
- a [custom mapping type](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/cookbook/custom-mapping-types.html). The methods should have proper non-empty-string type hints as described [here](https://github.com/phpstan/phpstan-doctrine#reflectiondescriptor)
- to register the new type with phpstan-doctrine using the ReflectionDescriptor, as described [here](https://github.com/phpstan/phpstan-doctrine#registering-type-descriptors)

If you want something simpler instead I would say just remove the `non-empty-string` annotation and use some assertions in your getters and setters to ensure the correct type.

**Comment by ondrejmirtes** [comment]
Hi, @AlexandruGG is right, this error is expected. There's no Doctrine database type that would guarantee you a non-empty-string. You're at the risk of Doctrine injecting `''` into your property.

**Comment by simPod** [comment]
I kind of don't see the issue here. PHPStan guards me agains assigning an empty string into the property and doctrine's `string` is able to store `non-empty-string` as it's covariant.

The extension should guard me against incompatible types, not subtypes.

Same with `integer` type. I can store `positive-int` there.

**Comment by ondrejmirtes** [comment]
@simPod Your database can contain something this property type doesn't want, and Doctrine will happily inject it there. That's what phpstan-doctrine is protecting you against.

**Comment by simPod** [comment]
It is not protecting me against this with json type either. Could it be somehow configurable? E.g. that I don't want errors for covariant types. I can guarantee nothing invalid will get injected there.

For now I'll solve by ignoring errors like this though that is a bit dirty.

**Comment by ondrejmirtes** [comment]
Can you open what issue with JSON type do you have?

**Comment by simPod** [comment]
This is the context for json type https://github.com/phpstan/phpstan-doctrine/commit/062fc75df9a393dc38a9722e0e8ab7036f5429ae there's no protection. And I don't think it's an issue, I think that's correct.

Overall, this kind of check is IMO too strict because it will not protect me anyways. E.g. I can change the column type in database which is the same situation as "Your database can contain something this property type doesn't want". I'm not protected against that either.

Consider

```php
    /**
     * @psalm-var integer
     *
     * @ORM\Column(type="integer")
     */
    private $val;
```

Where the column type is altered from `int` to `varchar`.
