### ISSUE TITLE
Support type infering of getArrayResult when selecting specific fields

### ISSUE THREAD

**Issue by janedbal** [phpstan/phpstan-doctrine#269]
Is there a possibility to support array hydration type infering when field list is selected? I can see it [actually works](https://github.com/phpstan/phpstan-doctrine/blob/master/tests/Type/Doctrine/data/QueryResult/queryResult.php#L113), but is not supported for `getArrayResult` nor `->getResult(AbstractQuery::HYDRATE_ARRAY)` even though the behaviour in doctrine is equal.

I can send failing tests if needed.

cc @arnaud-lb

**Comment by arnaud-lb** [comment]
Hi @janedbal 

Unfortunately, supporting more than one hydration mode is challenging for the reasons detailed [here](https://github.com/phpstan/phpstan-doctrine/pull/232#issuecomment-1015686749). So for now phpstan-doctrine supports only the `HYDRATE_OBJECT` mode.

As you pointed out, selecting individual fields is supported in `HYDRATE_OBJECT` mode, so in some cases it may be possible to use `getResult()` instead of `getArrayResult()`:

```
$query = $em->createQuery('
    SELECT e.foo, e.bar FROM Entity e
');

$query->getResult(); // array<array{foo: string, bar: string}>
```

**Comment by janedbal** [comment]
I see, thanks for quick response. 

Sidenote: Sad to hear that using (semantically) improper HYDRATE_OBJECT in those cases (it cannot hydrate objects when custom fields are selected) is the only working approach, but I think the benefits of type-inference is huge enough to convert our codebase to use that and write some phpstan rule to ensure that it in future.
