### ISSUE TITLE
Query result type inference often not working with getOneOrNullResult

### ISSUE THREAD

**Issue by janedbal** [phpstan/phpstan-doctrine#271]
See failures in https://github.com/phpstan/phpstan-doctrine/pull/270, all the new getOneOrNullResult are infered as mixed even though the getResult works fine.

E.g. [here](https://github.com/phpstan/phpstan-doctrine/runs/4965676150?check_suite_focus=true)

**Comment by arnaud-lb** [comment]
Hi @janedbal 

Currently, Query result type inference supports only `HYDRATE_OBJECT` mode. What happens here is that we don't know the hydration mode of `getOneOrNullResult()` when called with 0 arguments, because it defaults to `$this->_hydrationMode`.

`getResult()` is different because its default hydration mode is `HYDRATE_OBJECT`.

One way to get type inference out of `getOneOrNullResult()` is to specify the hydration mode when calling it: `getOneOrNullResult(Query::HYDRATE_OBJECT)`.

(See https://github.com/phpstan/phpstan-doctrine/pull/232#issuecomment-1015686749 for details on how each getResult() variant is supported.)

**Comment by janedbal** [comment]
I see, thanks for response, I'll force passing hydration type to getOneOrNullResult in our codebase to make it analysable.
