### ISSUE TITLE
`CASE WHEN EXISTS(...) THEN TRUE ELSE FALSE END AS my_column` is not inferred as boolean

### ISSUE THREAD

**Issue by yguedidi** [phpstan/phpstan-doctrine#311]
- Create an ORM QueryBuilder
- Call `->select('CASE WHEN EXISTS(SELECT 1) THEN TRUE ELSE FALSE END AS my_column')`
- Call `->getQuery()->getResult()`

See the type of `my_column` inferred as `0|'0'`

**Comment by stof** [comment]
It is still not inferred as a boolean, but as `0|1|'0'|'1'`

**Comment by arnaud-lb** [comment]
Unfortunately this is the actual type returned by Doctrine.

DQL `true` and `false` literals are transpiled to `1` and `0` in SQL, so `SELECT (true)` in DQL becomes `SELECT 1`.

After that, whether integers are returned as ints or strings depend on the driver, the driver settings, the Doctrine version, and the integer value. Currently the type inference simply assumes that integers can be returned as int|string.

That's why `true|false` in DQL is `0|1|'0'|'1'`.

**Comment by arnaud-lb** [comment]
Note: This fact about integers is only true for expressions (SELECT (true), SELECT MAX(...), etc) because Doctrine doesn't reinterprets the type of expressions results.

Doctrine does reinterpret the type of fields (SELECT x.foo), so selections of integer fields return `int` and selections or bigint fields return `string`.
