### ISSUE TITLE
Error with the return of repositories

### ISSUE THREAD

**Issue by rgrassian** [phpstan/phpstan-doctrine#413]
Hi,

I just upgraded from 1.3.29 to 1.3.31, and also doctrine/doctrine-bundle from 2.7.0 to 2.8.2
I have now errors with the `repository->findOneBy` method which returns now `object|null` instead of the expected entity or null.
I use an objectManagerLoader, I include `vendor/phpstan/phpstan-doctrine/extension.neon` and `vendor/phpstan/phpstan-doctrine/rules.neon`. I tried with and without bleedingEdge.

The errors disappear  when I downgrade the `StubFilesExtensionLoader->getFiles()` method and go back to the 
```
return 
[
    $path . '/ORM/QueryBuilder.stub',
    $path . '/EntityRepository.stub',
];

```

I saw that[ an other issue](https://github.com/phpstan/phpstan-doctrine/issues/409) was created and solved by 1.3.30 but it's still not ok for me.

**Comment by ondrejmirtes** [comment]
Please create a small reproducing repository that shows the problem.

**Comment by ste93cry** [comment]
I prepared the reproducing repo [here](https://github.com/ste93cry/phpstan-doctrine-issue-413-repro). Just run `vendor/bin/phpstan` and the error that comes out as result is:

```
Parameter #1 $fooEntity of method App\Controller\FooController::useFoo() expects App\Entity\FooEntity|null, object|null given.
```

**Comment by ondrejmirtes** [comment]
This should work now with PHPStan 1.9.11 and phpstan-doctrine 1.3.32. Please test it :)

The fix: https://github.com/phpstan/phpstan-doctrine/commit/6812cf44e0aff413df467c1a9d12e8ee9b8b192b

The background: Because of how the declaration of the class is conditional (https://github.com/doctrine/DoctrineBundle/blob/2.8.x/Repository/ServiceEntityRepository.php), PHPStan always sees the first definition (`class ServiceEntityRepository extends LazyServiceEntityRepository`).

But the previous logic in StubFilesExtensionLoader didn't reflect this, which means that the used stub said `@extends EntityRepository<TEntityClass>`, but because the rest of PHPStan saw `class ServiceEntityRepository extends LazyServiceEntityRepository`, it didn't use the `@extends` tag.

The new logic in StubFilesExtensionLoader should be resilient to this.

**Comment by ste93cry** [comment]
Thank you, it works!

**Comment by rgrassian** [comment]
Thank you @ondrejmirtes !
