### ISSUE TITLE
[Feature Request] Useless nullable annotation

### ISSUE THREAD

**Issue by sylfabre** [phpstan/phpstan-doctrine#451]
Hello

Here is a feature request to detect useless annotations:
- `@ORM\Column(nullable=false)`: default value is already `false` according to the doc (https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/annotations-reference.html#annref_column)
- `@ORM\JoinColumn(nullable=true)`: default value is already `true` according to the doc (https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/annotations-reference.html#annref_joincolumn)

Thanks!

**Comment by sylfabre** [comment]
And the same goes with `ORM\Column(type="string")` as `string` is the default type

**Comment by stof** [comment]
Reporting cases where an annotation (parsed with doctrine/annotations) has useless explicit configuration seems like a scope for a separate plugin IMO, instead of conflating all possible doctrine packages into the same plugin.
Currently, this plugin is all about the doctrine object manager projects.

doctrine/annotations is a totally separate package that is used by many other projects than the doctrine object manager projects (and it is targeted at a slow death in favor of attributes)

**Comment by alexander-schranz** [comment]
Just did stumble over this issue if you are using @rectorphp the `RemoveRedundantDefaultPropertyAnnotationValuesRector` rule covers this and will fix it automatically:

![Bildschirmfoto 2023-05-17 um 12 14 06](https://github.com/phpstan/phpstan-doctrine/assets/1698337/db881fd3-9d10-4a4a-86fd-ab2ecd83c75f)

Most people still think rector as only a refactoring tool but I really can recommend it to use it in daily way like phpstan, php-cs-fixer and other linters.

**Comment by sylfabre** [comment]
Thank you @alexander-schranz 
The rule was removed 3 weeks ago!
https://github.com/rectorphp/rector-doctrine/pull/196

I'm closing it as I agree with @stof comment

Thanks guys!
