### ISSUE TITLE
Doctrine QueryBulder typehint

### ISSUE THREAD

**Issue by simPod** [phpstan/phpstan-doctrine#5]
Level 5 gives me such warnings: `Parameter #4 $condition of method Doctrine\ORM\QueryBuilder::leftJoin() expects string|null, Doctrine\ORM\Query\Expr\Andx given`

That happens when you dont use simple string conditions like this `->leftJoin('u.Phonenumbers', 'p', Expr\Join::WITH, 'p.is_primary = 1');` while joining but when using Expr builder instead. QueryBuilder's join functions document that argument as string|null but it also takes Expr

Do you think I should mark this warning as ignored?

**Comment by stesie** [comment]
Well, the type signature of `leftJoin` clearly states `string|null`, and not some object. So if at all I think this is an issue with Doctrine ORM itself ... and it just works because the type implicitly is coerced to string.

On the project I'm currently on, we didn't mark the warning as ignored, but just explicitly cast the object to string, which calls the object's `__toString()` method.

**Comment by ondrejmirtes** [comment]
Yes, agreed, you should open a PR with Doctrine to update their phpDocs :)

**Comment by simPod** [comment]
I was looking into doctrine docs and I think it's better to cast to string as @stesie mentioned. For doctrine it would require huge rework for phpdocs. I believe it will improve with new doctrine major version
