### ISSUE TITLE
Comparing the database mapping type to the property type should take the phpstan level into account

### ISSUE THREAD

**Issue by stof** [phpstan/phpstan-doctrine#527]
`checkNull` is turned on only at level 8+ in phpstan. However, phpstan-doctrine complains about nullable properties vs non-nullable DB fields without taking this setting into account, which is inconsistent with the phpstan levels.
I think it would make sense to respect this phpstan setting in those comparisons.

**Comment by ondrejmirtes** [comment]
1) This feature has been out since 2019, and no one complained, which means it's generally pretty well received. I don't want to change it now.
2) This is reporting problems in declarations, not in usages. There are many examples of errors related to `null` which are reported on lower levels. This Doctrine error is much closer to this one https://phpstan.org/r/d15fb355-5750-4f6e-9549-8f5e851b63ef which is already reported on level 3.
