### ISSUE TITLE
Internal error: Class Doctrine\ORM\EntityRepository does not exist

### ISSUE THREAD

**Issue by josefsabl** [phpstan/phpstan-doctrine#58]
I'd like to open new issue here, but it was discussed after closing this issue: https://github.com/phpstan/phpstan-doctrine/issues/51

Looks like this plugin depends on the doctrine/orm although it definitely is useful for doctrine/odm as also stated in readme (Also supports Doctrine ODM.).

The fact is that it really works well for ODM project and I could delete a few ignore patterns. But I had to add doctrine/orm to my composer.json to make it work. Which is a shame.

I think it would not harm if this package added doctrine/orm as one of its own dependencies.

**Comment by ondrejmirtes** [comment]
> I think it would not harm if this package added doctrine/orm as one of its own dependencies.

It should not be solved like this, but instead asking if Doctrine ORM classes exist before using them.

**Comment by josefsabl** [comment]
Yeah, of course, that would be ideal :-)

**Comment by zacharra** [comment]
Hello,
is there any progress regarding this issue? In case it isn't obvious already, the issue is this line: https://github.com/phpstan/phpstan-doctrine/blob/95ffd1273b1020060a4cbe5e7f93c1eed4f24354/src/Reflection/Doctrine/EntityRepositoryClassReflectionExtension.php#L14 where isSubclassOf calls \ReflectionClass:isSubclassOf(), which expects the argument class to exist. It could be easily solved with a class_exists check before that, but I don't know if there is a better way, e.g. only conditionally load the extension or something.

**Comment by josefsabl** [comment]
> In case it isn't obvious already, the issue is this line:

Unfortunatelly changing this line to:

`|| (class_exists('Doctrine\ORM\EntityRepository') && $classReflection->isSubclassOf('Doctrine\ORM\EntityRepository'))`

Generates tons of other false positive errors.

**Comment by ondrejmirtes** [comment]
@josefsabl I don't know what false positives do you mean.

Fixed: https://github.com/phpstan/phpstan-doctrine/commit/98a70724aaa360657d62903434d0193ec4b09b8b

**Comment by josefsabl** [comment]
> I don't know what false positives do you mean.

Please disregard that post of mine. I just wanted to test the proposed solution by @zacharra only to find that it isn't that simple.
