### ISSUE TITLE
Doctrine and float and string

### ISSUE THREAD

**Issue by danielspk** [phpstan/phpstan-doctrine#71]
Hi, is it feasible for the plugin to detect Doctrine's behavior with respect to floats being handled as a string? Example:

```php
/**
 * @Entity
 */
class Demo
{
    /** @Column(type="decimal", precision=10, scale=2) */
    private $price;

    /**
     * Set price.
     *
     * @param string $number
     *
     * @return Demo
     */
    public function setPrice($number)
    {
        $this->price = $number;

        return $this;
    }
}

$demo = new Demo();
$demo->setPrice(0.0);
```

**Error output: Parameter #1 $number of method Demo::setPrice() expects string, float given**

Note: The Doctrine *orm: generate-entities* console command generates the method with its parameter as string.

Thanks.

**Comment by ondrejmirtes** [comment]
Hi, all types should be explicitly referenced in the code. If the Doctrine's decimal type accepts both string and float, you should have `string|float` in your setter parameter and as the property type.

But maybe you should stick to only strings, because floats are lossy? Or use something like https://github.com/moneyphp/money for this usecase.

See also reasoning behind https://github.com/Roave/no-floaters.

**Comment by danielspk** [comment]
Thank you. At the moment I am going to modify the signature of the DocBlock to *float|string* since I do not require floating point precision.
